import {
    AlarmClock,
    Apple,
    Banana,
    BarChart3,
    Archive,
    Boxes,
    BadgeCheck,
    Banknote,
    Beef,
    Beer,
    BeerOff,
    Briefcase,
    BriefcaseBusiness,
    Building,
    Building2,
    Calculator,
    CalendarCheck,
    CalendarClock,
    CalendarDays,
    CalendarFold,
    CalendarMinus,
    CalendarPlus,
    Candy,
    CandyCane,
    CandyOff,
    Cake,
    CakeSlice,
    Carrot,
    ChartBar,
    ChartPie,
    ChefHat,
    Cherry,
    Citrus,
    Clipboard,
    ClipboardCheck,
    ClipboardList,
    Coffee,
    CookingPot,
    Cookie,
    Croissant,
    CupSoda,
    Dessert,
    Donut,
    Drumstick,
    Egg,
    EggFried,
    EggOff,
    Edit3,
    FileSpreadsheet,
    FileText,
    Fish,
    FishOff,
    FishSymbol,
    Folder,
    FolderOpen,
    ForkKnife,
    ForkKnifeCrossed,
    GlassWater,
    Grape,
    Handshake,
    Headphones,
    Highlighter,
    IdCard,
    IceCream,
    IceCream2,
    IceCreamBowl,
    IceCreamCone,
    Laptop,
    Leaf,
    LeafyGreen,
    Lollipop,
    Mail,
    MailCheck,
    Martini,
    Milk,
    MilkOff,
    Monitor,
    Notebook,
    NotebookPen,
    NotebookTabs,
    NotebookText,
    Paperclip,
    Printer,
    Pen,
    PenLine,
    Pencil,
    PieChart,
    Pizza,
    Popcorn,
    Presentation,
    Ruler,
    Salad,
    Sandwich,
    Scissors,
    Slice,
    Smartphone,
    Soup,
    Sparkles,
    Sprout,
    Stamp,
    StickyNote,
    Tablet,
    Utensils,
    UtensilsCrossed,
    Vegan,
    Wallet,
    Wheat,
    WheatOff,
    Wine,
    WineOff,
} from "lucide-react";

export const CATEGORY_ICONS = [
    // Kitchen & equipment
    { value: "UtensilsCrossed", label: "Set Peralatan", icon: UtensilsCrossed },
    { value: "Utensils", label: "Peralatan Saji", icon: Utensils },
    { value: "ForkKnifeCrossed", label: "Garpu & Pisau", icon: ForkKnifeCrossed },
    { value: "ForkKnife", label: "Alat Makan", icon: ForkKnife },
    { value: "CookingPot", label: "Panci & Wajan", icon: CookingPot },
    { value: "ChefHat", label: "Chef Special", icon: ChefHat },
    { value: "GlassWater", label: "Gelas & Cangkir", icon: GlassWater },
    { value: "CupSoda", label: "Cup Minuman", icon: CupSoda },

    // Office & productivity
    { value: "Briefcase", label: "Bisnis", icon: Briefcase },
    { value: "BriefcaseBusiness", label: "Manajemen", icon: BriefcaseBusiness },
    { value: "Notebook", label: "Notebook", icon: Notebook },
    { value: "NotebookPen", label: "Catatan & Pena", icon: NotebookPen },
    { value: "NotebookText", label: "Catatan Teks", icon: NotebookText },
    { value: "NotebookTabs", label: "Notebook Tab", icon: NotebookTabs },
    { value: "Clipboard", label: "Clipboard", icon: Clipboard },
    { value: "ClipboardList", label: "Daftar Tugas", icon: ClipboardList },
    { value: "ClipboardCheck", label: "Checklist", icon: ClipboardCheck },
    { value: "StickyNote", label: "Sticky Note", icon: StickyNote },
    { value: "Highlighter", label: "Stabilo", icon: Highlighter },
    { value: "Pen", label: "Pena", icon: Pen },
    { value: "PenLine", label: "Tandai", icon: PenLine },
    { value: "Pencil", label: "Pensil", icon: Pencil },
    { value: "Edit3", label: "Edit", icon: Edit3 },
    { value: "Ruler", label: "Penggaris", icon: Ruler },
    { value: "Scissors", label: "Gunting", icon: Scissors },
    { value: "Paperclip", label: "Paperclip", icon: Paperclip },
    { value: "Mail", label: "Surat", icon: Mail },
    { value: "MailCheck", label: "Surat Disetujui", icon: MailCheck },
    { value: "CalendarDays", label: "Kalender", icon: CalendarDays },
    { value: "CalendarCheck", label: "Kalender Disetujui", icon: CalendarCheck },
    { value: "CalendarPlus", label: "Kalender Tambah", icon: CalendarPlus },
    { value: "CalendarMinus", label: "Kalender Kurang", icon: CalendarMinus },
    { value: "CalendarFold", label: "Kalender Lipat", icon: CalendarFold },
    { value: "CalendarClock", label: "Kalender Waktu", icon: CalendarClock },
    { value: "AlarmClock", label: "Alarm", icon: AlarmClock },
    { value: "FileText", label: "Dokumen", icon: FileText },
    { value: "FileSpreadsheet", label: "Spreadsheet", icon: FileSpreadsheet },
    { value: "Folder", label: "Folder", icon: Folder },
    { value: "FolderOpen", label: "Folder Terbuka", icon: FolderOpen },
    { value: "Archive", label: "Arsip", icon: Archive },
    { value: "Boxes", label: "Box Arsip", icon: Boxes },
    { value: "Printer", label: "Printer", icon: Printer },
    { value: "Monitor", label: "Monitor", icon: Monitor },
    { value: "Laptop", label: "Laptop", icon: Laptop },
    { value: "Tablet", label: "Tablet", icon: Tablet },
    { value: "Smartphone", label: "Smartphone", icon: Smartphone },
    { value: "Headphones", label: "Headset", icon: Headphones },
    { value: "Presentation", label: "Presentasi", icon: Presentation },
    { value: "ChartBar", label: "Grafik Batang", icon: ChartBar },
    { value: "ChartPie", label: "Grafik Pie", icon: ChartPie },
    { value: "BarChart3", label: "Chart 3", icon: BarChart3 },
    { value: "PieChart", label: "Analitik", icon: PieChart },
    { value: "IdCard", label: "ID Karyawan", icon: IdCard },
    { value: "BadgeCheck", label: "Sertifikasi", icon: BadgeCheck },
    { value: "Stamp", label: "Stempel", icon: Stamp },
    { value: "Calculator", label: "Kalkulator", icon: Calculator },
    { value: "Wallet", label: "Dompet", icon: Wallet },
    { value: "Banknote", label: "Pembayaran", icon: Banknote },
    { value: "Handshake", label: "Kemitraan", icon: Handshake },
    { value: "Building", label: "Gedung Kantor", icon: Building },
    { value: "Building2", label: "Tower Perkantoran", icon: Building2 },

    // Food & beverage
    { value: "Apple", label: "Buah Sehat", icon: Apple },
    { value: "Banana", label: "Buah Tropis", icon: Banana },
    { value: "Cherry", label: "Buah Ceri", icon: Cherry },
    { value: "Grape", label: "Buah Anggur", icon: Grape },
    { value: "Leaf", label: "Plant-Based", icon: Leaf },
    { value: "LeafyGreen", label: "Sayuran Hijau", icon: LeafyGreen },
    { value: "Carrot", label: "Vegetarian", icon: Carrot },
    { value: "Vegan", label: "Menu Vegan", icon: Vegan },
    { value: "Sprout", label: "Tunas Segar", icon: Sprout },
    { value: "Beef", label: "Daging Sapi", icon: Beef },
    { value: "Drumstick", label: "Olahan Ayam", icon: Drumstick },
    { value: "Fish", label: "Seafood", icon: Fish },
    { value: "FishOff", label: "Tanpa Seafood", icon: FishOff },
    { value: "FishSymbol", label: "Ikan Segar", icon: FishSymbol },
    { value: "Egg", label: "Menu Telur", icon: Egg },
    { value: "EggFried", label: "Telur Ceplok", icon: EggFried },
    { value: "EggOff", label: "Tanpa Telur", icon: EggOff },
    { value: "Pizza", label: "Pizza", icon: Pizza },
    { value: "Sandwich", label: "Sandwich", icon: Sandwich },
    { value: "Slice", label: "Potongan Roti", icon: Slice },
    { value: "Croissant", label: "Pastry", icon: Croissant },
    { value: "Soup", label: "Sup & Kuah", icon: Soup },
    { value: "Salad", label: "Salad", icon: Salad },
    { value: "Dessert", label: "Dessert Premium", icon: Dessert },
    { value: "Cake", label: "Kue Besar", icon: Cake },
    { value: "CakeSlice", label: "Potongan Kue", icon: CakeSlice },
    { value: "Donut", label: "Donat", icon: Donut },
    { value: "Candy", label: "Permen", icon: Candy },
    { value: "CandyCane", label: "Permen Natal", icon: CandyCane },
    { value: "CandyOff", label: "Tanpa Gula", icon: CandyOff },
    { value: "Cookie", label: "Camilan", icon: Cookie },
    { value: "Lollipop", label: "Lollipop", icon: Lollipop },
    { value: "Popcorn", label: "Popcorn", icon: Popcorn },
    { value: "IceCream", label: "Es Krim", icon: IceCream },
    { value: "IceCreamBowl", label: "Es Mangkok", icon: IceCreamBowl },
    { value: "IceCreamCone", label: "Es Cone", icon: IceCreamCone },
    { value: "IceCream2", label: "Gelato", icon: IceCream2 },
    { value: "Coffee", label: "Kopi & Teh", icon: Coffee },
    { value: "Citrus", label: "Minuman Segar", icon: Citrus },
    { value: "Martini", label: "Mocktail", icon: Martini },
    { value: "Beer", label: "Bir", icon: Beer },
    { value: "BeerOff", label: "Non-Alkohol", icon: BeerOff },
    { value: "Wine", label: "Wine", icon: Wine },
    { value: "WineOff", label: "Tanpa Wine", icon: WineOff },
    { value: "Milk", label: "Susu", icon: Milk },
    { value: "MilkOff", label: "Non-Dairy", icon: MilkOff },
    { value: "Sparkles", label: "Menu Signature", icon: Sparkles },
    { value: "Wheat", label: "Biji-Bijian", icon: Wheat },
    { value: "WheatOff", label: "Bebas Gluten", icon: WheatOff },
];

export const CATEGORY_ICON_MAP = CATEGORY_ICONS.reduce((map, item) => {
    map[item.value] = item.icon;
    return map;
}, {});

export const CATEGORY_ICON_LABEL_MAP = CATEGORY_ICONS.reduce((map, item) => {
    map[item.value] = item.label;
    return map;
}, {});
